apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q3dh7sfqt-java-quarkus
  janus-idp.io/tekton: q3dh7sfqt-java-quarkus
  backstage.io/kubernetes-id: q3dh7sfqt-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q3dh7sfqt-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
